learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url('register/',views.register,name='register'),
    url('user_login/',views.user_loginPls,name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfoModel(models.Model):

    #Creating a relation with the main model from admin, so we can add additional information
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfoModel

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoModelForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfoModel
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoModelForm

#imports
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
#changed from django.core.usrlresolvers to django.urls
#cant use reverse as it has been deprecated
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse('your logged in nice!!!')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoModelForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoModelForm()

    return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})



def user_loginPls(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('SOMEONE TRIED TO LOGIN AND FAILED')
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse('INVALID LOGIN DETAILS')
    else:
        return render(request,'basic_app/loginhtml.html',{})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <nav>
            <div class="container">
                <ul>
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a href="{% url 'basic_app:register' %}">Register</a></li>

                    {% if user.is_authenticated %}
                      <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                      <li><a href="{% url 'basic_app:user_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

    {% block body_block %}
    <div class="container">
        <h1>Django Level Five</h1>
        <h1>this is index</h1>
        {% if user.is_authenticated %}
          <h1>you're logged in</h1>
        {% else %}
          <h1>you're logged out</h1>
        {% endif %}
    </div>
    {% endblock %}

learning_users/templates/basic_app/loginhtml.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
    {% block body_block %}
    <h1>Please login</h1>
    <form action="{% url 'basic_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Username">

        <label for="password">Password: </label>
        <input type="password" name="password" value="">

        <input type="submit" name="" value="Login">
    </form>
    {% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

    {% block body_block %}
    <div class="container">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register here</h1>
            <h3>Fill out the form</h3>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}


    </div>
    {% endblock %}