social_clone/social_project/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'^signup/$',views.SignUp.as_view(),name='signup'),
]

social_clone/social_project/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns =[
    url(r'^$',views.PostlistView.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetailView.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

social_clone/social_project/social_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePageTemplateView.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    #for automatic authentication and not needing to register at admin.py for models mainly
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

social_clone/social_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Social Project</title>

        {# bootstrap #}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        {# JavaScript cdn #}
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {# google fonts #}
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        {# master css file #}
        <link rel="stylesheet" href="{% static "social_project/css/master.css" %}">



    </head>
    <body>
        <nav class="navbar mynav" role="navigation" id='navbar'>
            <div class="container">
                <a class="navbar-brand mynav" href="{% url 'home' %}">Social Project</a>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'posts:create' %}">Post</a>
                        </li>
                        <li>
                            <a href="{% url 'groups:all' %}">Groups</a>
                        </li>
                        <li>
                            <a href="{% url 'groups:create' %}">Create Group</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'groups:all' %}">Groups</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:login' %}">Log In</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Sign Up</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </nav>
        <div class="container mycontent">
            {% block content %}
            {% endblock  %}
        </div>
        <canvas id="canvas"></canvas>
            <script  src="{% static "social_project/js/master.js" %}"></script>
    </body>

</html>

social_clone/social_project/templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome to Star Social!</h1>
{% endblock  %}

social_clone/social_project/templates/test.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>You are now Logged in</h1>
    </div>
{% endblock  %}

social_clone/social_project/templates/thanks.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Thanks for visiting, come back soon!</h1>
    </div>
{% endblock  %}