social_clone/social_project/groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$',views.ListGroups.as_view(),name='all'),
    url(r'new/$',views.CreateGroup.as_view(),name='create'),
    url(r'posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single'),
    url(r'leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name='leave'),
    url(r'join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name='join'),
]

social_clone/social_project/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns =[
    url(r'^$',views.PostlistView.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetailView.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

social_clone/social_project/social_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePageTemplateView.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    #for automatic authentication and not needing to register at admin.py for models mainly
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

social_clone/social_project/groups/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django.urls import reverse

from django.contrib.auth import get_user_model
#creating a current user logged in object
User = get_user_model()

from django import template

#for creating custom template
register = template.Library()
# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)
    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']
        
class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='membership',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

social_clone/social_project/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
# or this way is also valid
# from django.views.generic import (
#                                     TemplateView,
#                                     ListView,
#                                     DetailView,
#                                     CreateView,
#                                     UpdateView,
#                                     DeleteView,
# )
from .models import Group, GroupMember
from django.shortcuts import get_object_or_404
from django.contrib import messages
# Create your views here.

class CreateGroup(LoginRequiredMixin,generic.CreateView):
        model = Group
        fields = ('name','description')
        redirect_field_name = 'groups/group_detail.html'

class SingleGroup(generic.DetailView):
    model = Group
    context_object_name = 'group_detail_context'
    template_name = 'groups/group_detail.html'

class ListGroups(generic.ListView):
    model = Group
    context_object_name = 'group_list_context'
    template_name = 'groups/group_list.html'

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,'Warning already a member!')
        else:
            messages.success(self.request,'You are now a member!')
        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        # group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        # or
        try:
            membership = GroupMember.objects.filter(
            user = self.request.user,
            group__slug = self.kwargs.get('slug')
            ).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are\'nt in this group')
        else:
            membership.delete()
            messages.success(self.request,'Successfully left this group')
        return super().get(request,*args,**kwargs)

social_clone/social_project/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            {% block pregroup %}{% endblock %}
            {% block group_content %}{% endblock %}
            {% block postgroup %}{% endblock %}
        </div>
    </div>
{% endblock  %}

social_clone/social_project/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
    <h1>{{group_detail_context.name}}</h1>
    <h2>Member count: {{group_detail_context.members.count}}</h2>

    <div class="content">
        {% if user in group_detail_context.members.all %}
            <a href="{% url 'groups:leave' slug=group_detail_context.slug %}" class="btn btn-lg btn-fill btn-warning">Leave Group</a>
        {% else %}
            <a href="{% url 'groups:join' slug=group_detail_context.slug %}" class="btn btn-lg btn-fill btn-default">Join Group</a>
        {% endif %}
    </div>
{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        {% if group_detail_context.posts.count == 0 %}
            <h2>No posts in this group yet</h2>
        {% else %}
            {% for post in group_detail_context.posts.all  %}
                {% include "posts/_post.html" %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}
{% block postgroup %}
<div class="col-md-4">
    <h2>GROUP MEMBERS</h2>
    <ol>
    {% for group_user in group_detail_context.members.all %}
            <li>
                <h3>
                    <a href="{% url 'posts:for_user' username=group_user.username %}">@{{group_user.username}}</a>
                </h3>
            </li>
    {% endfor %}
    </ol>
</div>
{% endblock %}

social_clone/social_project/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
    <h4>Create a new group!</h4>
    <form action="{% url 'groups:create' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-large" value="Create">
    </form>
{% endblock %}

social_clone/social_project/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>
                    Welcome back!!
                    <a href="{% url 'posts:for_user' username=user.username %}">
                        @{{user.username}}
                    </a>
                </h2>
            {% endif %}
            <h2>Groups</h2>
            <p>Welcome to the groups page!</p>
        </div>
    </div>
    {% if user.is_authenticated %}
        <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">Create New Group!</a>
    {% endif %}
{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
            {% for group in group_list_context  %}
                <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
                    <h3 class="title list-group-item-heading">{{group.name}}</h3>
                    <div class="list-group-item-text container-fluid">
                        {{group.description_html|safe}}
                        <div class="row">
                            <div class="col-md-4">
                                <span class="badge">
                                    {{group.members.count}}
                                </span>
                                member{{group.members.count|pluralize}}
                            </div>
                            <div class="col-md-4">
                                <span class="badge">
                                    {{group.posts.count}}
                                </span>
                                post{{group.posts.count|pluralize}}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}

        </div>
    </div>
{% endblock %}